CREATE SEQUENCE IF NOT EXISTS Submission_seq START WITH 1 INCREMENT BY 50;

CREATE SEQUENCE IF NOT EXISTS TestCase_seq START WITH 1 INCREMENT BY 50;

CREATE TABLE Contest
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                   VARCHAR(255)                            NOT NULL,
    startDate              TIMESTAMP WITHOUT TIME ZONE,
    endDate                TIMESTAMP WITHOUT TIME ZONE,
    roomId                 BIGINT,
    upsolvingAfterFinished BOOLEAN                                 NOT NULL,
    upsolving              BOOLEAN                                 NOT NULL,
    scoringType            SMALLINT                                NOT NULL,
    version                INTEGER,
    CONSTRAINT pk_contest PRIMARY KEY (id)
);

CREATE TABLE Contest_participants
(
    Contest_id      BIGINT NOT NULL,
    participants_id BIGINT NOT NULL
);

CREATE TABLE Contest_task
(
    Contest_id BIGINT NOT NULL,
    tasks_id   BIGINT NOT NULL
);

CREATE TABLE Post
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title     VARCHAR(255)                            NOT NULL,
    content   TEXT                                    NOT NULL,
    author_id BIGINT,
    postDate  TIMESTAMP WITHOUT TIME ZONE,
    roomId    BIGINT,
    CONSTRAINT pk_post PRIMARY KEY (id)
);

CREATE TABLE RecoverPassword
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    userId     BIGINT                                  NOT NULL,
    used       BOOLEAN                                 NOT NULL,
    link       VARCHAR(255),
    createTime TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_recoverpassword PRIMARY KEY (id)
);

CREATE TABLE Submission
(
    id                 BIGINT       NOT NULL,
    user_id            BIGINT,
    task_id            BIGINT,
    contest_id         BIGINT,
    fileName           VARCHAR(255) NOT NULL,
    language           VARCHAR(255) NOT NULL,
    submissionTime     TIMESTAMP WITHOUT TIME ZONE,
    submissionMemory   INTEGER,
    status             SMALLINT     NOT NULL,
    score              FLOAT,
    compilationResult  VARCHAR(255),
    compilationMessage VARCHAR(255),
    currentTest        INTEGER,
    roomId             BIGINT,
    CONSTRAINT pk_submission PRIMARY KEY (id)
);

CREATE TABLE Submission_submissionTestResults
(
    Submission_id BIGINT NOT NULL,
    score         FLOAT,
    testKey       VARCHAR(255),
    outcome       VARCHAR(255),
    message       VARCHAR(255),
    time          INTEGER,
    memory        INTEGER,
    testStatus    SMALLINT
);

CREATE TABLE Task
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contest_id         BIGINT,
    title              VARCHAR(255),
    configAddress      VARCHAR(255),
    taskType           SMALLINT,
    taskScoreType      SMALLINT,
    taskScoreParameter VARCHAR(255),
    timeLimitMillis    INTEGER,
    memoryLimitMB      INTEGER,
    inputTemplate      VARCHAR(255),
    outputTemplate     VARCHAR(255),
    code               VARCHAR(255),
    CONSTRAINT pk_task PRIMARY KEY (id)
);

CREATE TABLE Task_statements
(
    Task_id        BIGINT   NOT NULL,
    statements     VARCHAR(25500),
    statements_key SMALLINT NOT NULL,
    CONSTRAINT pk_task_statements PRIMARY KEY (Task_id, statements_key)
);

CREATE TABLE Task_testCase
(
    Task_id      BIGINT NOT NULL,
    testCases_id BIGINT NOT NULL
);

CREATE TABLE TestCase
(
    id                BIGINT NOT NULL,
    key               VARCHAR(255),
    taskId            BIGINT,
    inputFileAddress  VARCHAR(255),
    OutputFileAddress VARCHAR(255),
    CONSTRAINT pk_testcase PRIMARY KEY (id)
);

CREATE TABLE contest_room
(
    id   BIGINT       NOT NULL,
    name VARCHAR(255) NOT NULL,
    open BOOLEAN      NOT NULL,
    CONSTRAINT pk_contest_room PRIMARY KEY (id)
);

CREATE TABLE contest_room_participants
(
    contest_room_id BIGINT NOT NULL,
    participants_id BIGINT NOT NULL,
    CONSTRAINT pk_contest_room_participants PRIMARY KEY (contest_room_id, participants_id)
);

CREATE TABLE contest_room_teachers
(
    contest_room_id BIGINT NOT NULL,
    teachers_id     BIGINT NOT NULL,
    CONSTRAINT pk_contest_room_teachers PRIMARY KEY (contest_room_id, teachers_id)
);

CREATE TABLE contestant_result
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contestantId         BIGINT                                  NOT NULL,
    contest_id           BIGINT                                  NOT NULL,
    totalScore           FLOAT                                   NOT NULL,
    upsolving_contest_id BIGINT,
    CONSTRAINT pk_contestant_result PRIMARY KEY (id)
);

CREATE TABLE principal
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    username      VARCHAR(255)                            NOT NULL,
    password      VARCHAR(255)                            NOT NULL,
    password_salt VARCHAR(255)                            NOT NULL,
    first_name    VARCHAR(255)                            NOT NULL,
    last_name     VARCHAR(255)                            NOT NULL,
    role          VARCHAR(255)                            NOT NULL,
    email         VARCHAR(255)                            NOT NULL,
    version       INTEGER,
    CONSTRAINT pk_principal PRIMARY KEY (id)
);

CREATE TABLE task_results
(
    standings_id BIGINT       NOT NULL,
    taskCode     VARCHAR(255),
    score        FLOAT,
    attempts     INTEGER,
    successTime  BIGINT,
    task_code    VARCHAR(255) NOT NULL,
    CONSTRAINT pk_task_results PRIMARY KEY (standings_id, task_code)
);

ALTER TABLE Contest
    ADD CONSTRAINT uc_contest_name UNIQUE (name);

ALTER TABLE Contest_participants
    ADD CONSTRAINT uc_contest_participants_participants UNIQUE (participants_id);

ALTER TABLE contest_room
    ADD CONSTRAINT uc_contest_room_name UNIQUE (name);

ALTER TABLE contest_room_participants
    ADD CONSTRAINT uc_contest_room_participants_participants UNIQUE (participants_id);

ALTER TABLE contest_room_teachers
    ADD CONSTRAINT uc_contest_room_teachers_teachers UNIQUE (teachers_id);

ALTER TABLE Contest_task
    ADD CONSTRAINT uc_contest_task_tasks UNIQUE (tasks_id);

ALTER TABLE principal
    ADD CONSTRAINT uc_principal_username UNIQUE (username);

ALTER TABLE Task
    ADD CONSTRAINT uc_task_code UNIQUE (code);

ALTER TABLE Task_testCase
    ADD CONSTRAINT uc_task_testcase_testcases UNIQUE (testCases_id);

CREATE INDEX idx_total_score ON contestant_result (totalScore);

ALTER TABLE contestant_result
    ADD CONSTRAINT FK_CONTESTANT_RESULT_ON_CONTEST FOREIGN KEY (contest_id) REFERENCES Contest (id);

ALTER TABLE contestant_result
    ADD CONSTRAINT FK_CONTESTANT_RESULT_ON_UPSOLVING_CONTEST FOREIGN KEY (upsolving_contest_id) REFERENCES Contest (id);

ALTER TABLE Post
    ADD CONSTRAINT FK_POST_ON_AUTHOR FOREIGN KEY (author_id) REFERENCES principal (id);

ALTER TABLE Submission
    ADD CONSTRAINT FK_SUBMISSION_ON_CONTEST FOREIGN KEY (contest_id) REFERENCES Contest (id);

ALTER TABLE Submission
    ADD CONSTRAINT FK_SUBMISSION_ON_TASK FOREIGN KEY (task_id) REFERENCES Task (id);

ALTER TABLE Submission
    ADD CONSTRAINT FK_SUBMISSION_ON_USER FOREIGN KEY (user_id) REFERENCES principal (id);

ALTER TABLE Task
    ADD CONSTRAINT FK_TASK_ON_CONTEST FOREIGN KEY (contest_id) REFERENCES Contest (id);

ALTER TABLE Contest_participants
    ADD CONSTRAINT fk_conpar_on_contest FOREIGN KEY (Contest_id) REFERENCES Contest (id);

ALTER TABLE Contest_participants
    ADD CONSTRAINT fk_conpar_on_user FOREIGN KEY (participants_id) REFERENCES principal (id);

ALTER TABLE contest_room_participants
    ADD CONSTRAINT fk_conroopar_on_contest_room FOREIGN KEY (contest_room_id) REFERENCES contest_room (id);

ALTER TABLE contest_room_participants
    ADD CONSTRAINT fk_conroopar_on_user FOREIGN KEY (participants_id) REFERENCES principal (id);

ALTER TABLE contest_room_teachers
    ADD CONSTRAINT fk_conrootea_on_contest_room FOREIGN KEY (contest_room_id) REFERENCES contest_room (id);

ALTER TABLE contest_room_teachers
    ADD CONSTRAINT fk_conrootea_on_user FOREIGN KEY (teachers_id) REFERENCES principal (id);

ALTER TABLE Contest_task
    ADD CONSTRAINT fk_contas_on_contest FOREIGN KEY (Contest_id) REFERENCES Contest (id);

ALTER TABLE Contest_task
    ADD CONSTRAINT fk_contas_on_task FOREIGN KEY (tasks_id) REFERENCES Task (id);

ALTER TABLE Submission_submissionTestResults
    ADD CONSTRAINT fk_submission_submissiontestresults_on_submission FOREIGN KEY (Submission_id) REFERENCES Submission (id);

ALTER TABLE task_results
    ADD CONSTRAINT fk_task_results_on_contestant_result FOREIGN KEY (standings_id) REFERENCES contestant_result (id);

ALTER TABLE Task_statements
    ADD CONSTRAINT fk_task_statements_on_task FOREIGN KEY (Task_id) REFERENCES Task (id);

ALTER TABLE Task_testCase
    ADD CONSTRAINT fk_tastes_on_task FOREIGN KEY (Task_id) REFERENCES Task (id);

ALTER TABLE Task_testCase
    ADD CONSTRAINT fk_tastes_on_test_case FOREIGN KEY (testCases_id) REFERENCES TestCase (id);